# Docker Optimizer Logging Configuration

version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "message": "%(message)s", "module": "%(module)s", "function": "%(funcName)s", "line": %(lineno)d}'
    datefmt: '%Y-%m-%dT%H:%M:%S'
    
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(funcName)s() - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
    
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: /var/log/docker-optimizer/app.log
    maxBytes: 104857600  # 100MB
    backupCount: 10
    encoding: utf8
    
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: /var/log/docker-optimizer/error.log
    maxBytes: 52428800  # 50MB
    backupCount: 5
    encoding: utf8

loggers:
  docker_optimizer:
    level: INFO
    handlers: [console, file, error_file]
    propagate: false
    
  docker_optimizer.security:
    level: WARNING
    handlers: [file, error_file]
    propagate: false
    
  docker_optimizer.performance:
    level: DEBUG
    handlers: [file]
    propagate: false

root:
  level: INFO
  handlers: [console, file]